/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckInboxRouteImport } from './routes/check-inbox'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizerIndexRouteImport } from './routes/organizer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OrganizerTournamentsRouteImport } from './routes/organizer.tournaments'
import { Route as OrganizerNewRouteImport } from './routes/organizer.new'
import { Route as AdminStoresRouteImport } from './routes/admin.stores'
import { Route as AdminPublishRouteImport } from './routes/admin.publish'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminApprovedRouteImport } from './routes/admin.approved'
import { Route as AdminPlayersIdRouteImport } from './routes/admin.players.$id'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInboxRoute = CheckInboxRouteImport.update({
  id: '/check-inbox',
  path: '/check-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OrganizerTournamentsRoute = OrganizerTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerNewRoute = OrganizerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrganizerRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublishRoute = AdminPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovedRoute = AdminApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersIdRoute = AdminPlayersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPlayersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/check-inbox': typeof CheckInboxRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/organizer': typeof OrganizerRouteWithChildren
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/admin/approved': typeof AdminApprovedRoute
  '/admin/players': typeof AdminPlayersRouteWithChildren
  '/admin/publish': typeof AdminPublishRoute
  '/admin/stores': typeof AdminStoresRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/organizer/tournaments': typeof OrganizerTournamentsRoute
  '/admin/': typeof AdminIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/admin/players/$id': typeof AdminPlayersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-inbox': typeof CheckInboxRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/admin/approved': typeof AdminApprovedRoute
  '/admin/players': typeof AdminPlayersRouteWithChildren
  '/admin/publish': typeof AdminPublishRoute
  '/admin/stores': typeof AdminStoresRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/organizer/tournaments': typeof OrganizerTournamentsRoute
  '/admin': typeof AdminIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/admin/players/$id': typeof AdminPlayersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/check-inbox': typeof CheckInboxRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/organizer': typeof OrganizerRouteWithChildren
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/admin/approved': typeof AdminApprovedRoute
  '/admin/players': typeof AdminPlayersRouteWithChildren
  '/admin/publish': typeof AdminPublishRoute
  '/admin/stores': typeof AdminStoresRoute
  '/organizer/new': typeof OrganizerNewRoute
  '/organizer/tournaments': typeof OrganizerTournamentsRoute
  '/admin/': typeof AdminIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/admin/players/$id': typeof AdminPlayersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/check-inbox'
    | '/dashboard'
    | '/login'
    | '/organizer'
    | '/setup'
    | '/signup'
    | '/upload'
    | '/admin/approved'
    | '/admin/players'
    | '/admin/publish'
    | '/admin/stores'
    | '/organizer/new'
    | '/organizer/tournaments'
    | '/admin/'
    | '/organizer/'
    | '/admin/players/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-inbox'
    | '/dashboard'
    | '/login'
    | '/setup'
    | '/signup'
    | '/upload'
    | '/admin/approved'
    | '/admin/players'
    | '/admin/publish'
    | '/admin/stores'
    | '/organizer/new'
    | '/organizer/tournaments'
    | '/admin'
    | '/organizer'
    | '/admin/players/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/check-inbox'
    | '/dashboard'
    | '/login'
    | '/organizer'
    | '/setup'
    | '/signup'
    | '/upload'
    | '/admin/approved'
    | '/admin/players'
    | '/admin/publish'
    | '/admin/stores'
    | '/organizer/new'
    | '/organizer/tournaments'
    | '/admin/'
    | '/organizer/'
    | '/admin/players/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckInboxRoute: typeof CheckInboxRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OrganizerRoute: typeof OrganizerRouteWithChildren
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-inbox': {
      id: '/check-inbox'
      path: '/check-inbox'
      fullPath: '/check-inbox'
      preLoaderRoute: typeof CheckInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/organizer/tournaments': {
      id: '/organizer/tournaments'
      path: '/tournaments'
      fullPath: '/organizer/tournaments'
      preLoaderRoute: typeof OrganizerTournamentsRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/new': {
      id: '/organizer/new'
      path: '/new'
      fullPath: '/organizer/new'
      preLoaderRoute: typeof OrganizerNewRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/publish': {
      id: '/admin/publish'
      path: '/publish'
      fullPath: '/admin/publish'
      preLoaderRoute: typeof AdminPublishRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approved': {
      id: '/admin/approved'
      path: '/approved'
      fullPath: '/admin/approved'
      preLoaderRoute: typeof AdminApprovedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players/$id': {
      id: '/admin/players/$id'
      path: '/$id'
      fullPath: '/admin/players/$id'
      preLoaderRoute: typeof AdminPlayersIdRouteImport
      parentRoute: typeof AdminPlayersRoute
    }
  }
}

interface AdminPlayersRouteChildren {
  AdminPlayersIdRoute: typeof AdminPlayersIdRoute
}

const AdminPlayersRouteChildren: AdminPlayersRouteChildren = {
  AdminPlayersIdRoute: AdminPlayersIdRoute,
}

const AdminPlayersRouteWithChildren = AdminPlayersRoute._addFileChildren(
  AdminPlayersRouteChildren,
)

interface AdminRouteChildren {
  AdminApprovedRoute: typeof AdminApprovedRoute
  AdminPlayersRoute: typeof AdminPlayersRouteWithChildren
  AdminPublishRoute: typeof AdminPublishRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovedRoute: AdminApprovedRoute,
  AdminPlayersRoute: AdminPlayersRouteWithChildren,
  AdminPublishRoute: AdminPublishRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrganizerRouteChildren {
  OrganizerNewRoute: typeof OrganizerNewRoute
  OrganizerTournamentsRoute: typeof OrganizerTournamentsRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
}

const OrganizerRouteChildren: OrganizerRouteChildren = {
  OrganizerNewRoute: OrganizerNewRoute,
  OrganizerTournamentsRoute: OrganizerTournamentsRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
}

const OrganizerRouteWithChildren = OrganizerRoute._addFileChildren(
  OrganizerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckInboxRoute: CheckInboxRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OrganizerRoute: OrganizerRouteWithChildren,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
